"""added profile support for users

Revision ID: 010e09329088
Revises: set_wholesale_defaults
Create Date: 2024-11-18 11:55:37.133792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010e09329088'
down_revision: Union[str, None] = 'set_wholesale_defaults'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_email_key', 'profiles', type_='unique')
    op.add_column('users', sa.Column('initial_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('has_changed_password', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_changed_password')
    op.drop_column('users', 'initial_password')
    op.create_unique_constraint('profiles_email_key', 'profiles', ['email'])
    # ### end Alembic commands ###
