"""convert date columns to timestamp

Revision ID: 078d9625a1d7
Revises: 513a1543956b
Create Date: 2024-11-06 01:56:11.379425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078d9625a1d7'
down_revision: Union[str, None] = '513a1543956b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invreports', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('invreports', 'last_edit',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('invreports', 'date_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invreports', sa.Column('date_created', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('invreports', 'last_edit',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('invreports', 'created_at')
    # ### end Alembic commands ###
