"""added low stock threshold column

Revision ID: 092883a7a98d
Revises: 37b1a7503714
Create Date: 2024-11-10 20:38:36.607091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092883a7a98d'
down_revision: Union[str, None] = '37b1a7503714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), nullable=True))
    op.drop_column('products', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'low_stock_threshold')
    # ### end Alembic commands ###
