"""added image_url nullable column to products

Revision ID: 0ff98b8ddac2
Revises: d9dd7e6fd26d
Create Date: 2024-12-18 08:29:18.542267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff98b8ddac2'
down_revision: Union[str, None] = 'd9dd7e6fd26d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
