"""added current_expiration_date property and product batch table

Revision ID: 1629b009b154
Revises: b2308639bd17
Create Date: 2024-11-06 23:42:18.299746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1629b009b154'
down_revision: Union[str, None] = 'b2308639bd17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch_products', 'expiration_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch_products', sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
