"""removed image link column in product table

Revision ID: 422067142f8d
Revises: 32ab1a31caa6
Create Date: 2024-12-18 06:34:40.375911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422067142f8d'
down_revision: Union[str, None] = '32ab1a31caa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
