"""added a seperate payments table for transactions to track individual payment

Revision ID: 44c354155ff2
Revises: a583c9b98cf2
Create Date: 2024-11-22 20:31:24.114226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c354155ff2'
down_revision: Union[str, None] = 'a583c9b98cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('is_void', sa.Boolean(), nullable=True))
    op.add_column('payments', sa.Column('void_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'void_reason')
    op.drop_column('payments', 'is_void')
    # ### end Alembic commands ###
