"""remove tin number unique constraint

Revision ID: 48813ab64e97
Revises: manual_profile_setup
Create Date: 2024-11-18 22:11:48.151040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48813ab64e97'
down_revision: Union[str, None] = 'manual_profile_setup'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_tin_number_key', 'clients', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('clients_tin_number_key', 'clients', ['tin_number'])
    # ### end Alembic commands ###
