"""add branch_id to users table

Revision ID: 513a1543956b
Revises: 5e74329e7949
Create Date: 2024-11-03 12:01:02.245544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513a1543956b'
down_revision: Union[str, None] = '5e74329e7949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'branch_est')
    op.add_column('users', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'branch_id')
    op.add_column('branches', sa.Column('branch_est', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
