"""removed pullout column since they are now computed

Revision ID: 715171773955
Revises: 7d6ce28e197c
Create Date: 2024-11-07 14:42:22.958522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715171773955'
down_revision: Union[str, None] = '7d6ce28e197c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invreport_items', 'pull_out')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invreport_items', sa.Column('pull_out', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
