"""removed deliver and transfer column from invreportitem since they are now computed

Revision ID: 7d6ce28e197c
Revises: 8403a08c4c94
Create Date: 2024-11-07 09:04:47.476785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6ce28e197c'
down_revision: Union[str, None] = '8403a08c4c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
