"""added inventory report batch table

Revision ID: 8403a08c4c94
Revises: dedupe_batches
Create Date: 2024-11-07 08:29:26.154489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8403a08c4c94'
down_revision: Union[str, None] = 'dedupe_batches'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invreport_items', 'transfer')
    op.drop_column('invreport_items', 'deliver')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invreport_items', sa.Column('deliver', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('invreport_items', sa.Column('transfer', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
