"""added app versions table for apk uploads

Revision ID: aac857bca7a6
Revises: e1b8dbf63cb0
Create Date: 2024-12-19 22:27:37.628013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac857bca7a6'
down_revision: Union[str, None] = 'e1b8dbf63cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
