"""added the is_active column to branches table

Revision ID: ab41ef220c3b
Revises: f4af9321c89e
Create Date: 2024-10-06 08:19:12.787383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab41ef220c3b'
down_revision: Union[str, None] = 'f4af9321c89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'is_active')
    # ### end Alembic commands ###
