"""add wholesale support

Revision ID: be7843c76fa2
Revises: 37136e077035
Create Date: 2024-11-16 19:44:17.780336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7843c76fa2'
down_revision: Union[str, None] = '37136e077035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('branch_type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('retail_low_stock_threshold', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('wholesale_low_stock_threshold', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_retail_available', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_wholesale_available', sa.Boolean(), nullable=True))
    op.drop_column('products', 'low_stock_threshold')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('low_stock_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'is_wholesale_available')
    op.drop_column('products', 'is_retail_available')
    op.drop_column('products', 'wholesale_low_stock_threshold')
    op.drop_column('products', 'retail_low_stock_threshold')
    op.drop_column('branches', 'branch_type')
    # ### end Alembic commands ###
