"""removed expiration date column, expiration is now computed to be the earliest expiration on batches of products

Revision ID: cef0d13876ce
Revises: 1629b009b154
Create Date: 2024-11-07 01:46:52.712779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef0d13876ce'
down_revision: Union[str, None] = '1629b009b154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
