"""replaced notes to be reason for voiding

Revision ID: e3c25e97b317
Revises: 48813ab64e97
Create Date: 2024-11-20 01:55:17.888427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c25e97b317'
down_revision: Union[str, None] = '48813ab64e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_items_batch_id_fkey', 'transaction_items', type_='foreignkey')
    op.drop_column('transaction_items', 'batch_id')
    op.add_column('transactions', sa.Column('void_reason', sa.String(), nullable=True))
    op.drop_column('transactions', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'void_reason')
    op.add_column('transaction_items', sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transaction_items_batch_id_fkey', 'transaction_items', 'product_batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###
