"""added a suppliers table

Revision ID: f22d82a3a71d
Revises: 44c354155ff2
Create Date: 2024-11-23 01:13:03.368093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22d82a3a71d'
down_revision: Union[str, None] = '44c354155ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('contact_person', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('suppliers', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('suppliers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('suppliers', 'updated_at')
    op.drop_column('suppliers', 'created_at')
    op.drop_column('suppliers', 'notes')
    op.drop_column('suppliers', 'is_active')
    op.drop_column('suppliers', 'contact_person')
    # ### end Alembic commands ###
