"""modify invreport columns, removed status and last edit, added coverage date

Revision ID: fa123e1ec802
Revises: data_conversion_timestamp
Create Date: 2024-11-06 02:48:03.360653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa123e1ec802'
down_revision: Union[str, None] = 'data_conversion_timestamp'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invreports', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('invreports', sa.Column('end_date', sa.Date(), nullable=True))
    op.drop_column('invreports', 'last_edit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invreports', sa.Column('last_edit', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('invreports', 'end_date')
    op.drop_column('invreports', 'start_date')
    # ### end Alembic commands ###
