"""added nullables in the products column

Revision ID: fbc4f2b00708
Revises: 0ff98b8ddac2
Create Date: 2024-12-18 08:44:57.559942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc4f2b00708'
down_revision: Union[str, None] = '0ff98b8ddac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('products', 'srp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('products', 'retail_low_stock_threshold',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'wholesale_low_stock_threshold',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'is_retail_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'is_wholesale_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'is_wholesale_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'is_retail_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'wholesale_low_stock_threshold',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'retail_low_stock_threshold',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'srp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('products', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
