name: Deploy FastAPI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Start FASTAPI
        run: |
          cd /home/pomona
          ./run_fastapi.sh
